title: biscuit's personal blog
description: This is where I'm going to share stuff that happened in my life hopefully.
author: "Rafael F."

theme: minima

# Minima social links
github_username: b1scoito
telegram_username: biscoito

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
